<?php


/**
 *	Impliment hook_menu().
 */

 function menu_form_menu() {
 	$items = array();

 	$items['link_to_form'] = array(
 		'title' => 'Link To Form',
 		'type' => MENU_NORMAL_ITEM,
 		'access arguments' => array('access content'),
 		'page callback' => 'drupal_get_form',
 		'page arguments' => array('menu_form_basic'),
 		'file' => 'my_menu.form.inc'
 	);
 	$items['form_submission'] = array(
 		'title' => 'Form Submission',
 		'type' => MENU_NORMAL_ITEM,
 		'access arguments' => array('access content'),
 		'page callback' => 'form_data_submission',

 	);

 	return $items;
 }

/**
 *	view form submissions.
 */

function form_data_submission() {
	// $results = db_query("SELECT * FROM {visitor_info}");

	$query = db_select('user_info', 'fd');
	$query
		->fields('fd', array('uid', 'fname', 'lname', 'uemail', 'Language', 'gen', 'nationality', 'cdate', 'dob'))
		->range(0, 50)
		->orderBy('fd.uid');
	$results = $query->execute();

	$header = array(t('ID'), t('First Name'), t('Last Name'), t('Email'), t('Language'), t('Gen'), t('Nationality'), t('Submited Date'), t('Date Of Birth'));
	$row = array();

	foreach ($results as $result) {
		$timestampcdate =  date('D, d M Y' , $result->cdate);
		$timestampdob =  date('D, d M Y' , $result->dob);
		$row[] =array(
			$result->uid,
			$result->fname,
			$result->lname,
			$result->uemail,
			$result->Language,
			$result->gen,
			$result->nationality,
			$timestampcdate,
			$timestampdob,
		);
	}
	return theme('table', array('header' => $header, 'rows' => $row));
}